-- MySQL Script generated by MySQL Workbench
-- 01/07/16 12:44:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MoverViejitosdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MoverViejitosdb` ;

-- -----------------------------------------------------
-- Schema MoverViejitosdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MoverViejitosdb` DEFAULT CHARACTER SET utf8 ;
USE `MoverViejitosdb` ;

-- -----------------------------------------------------
-- Table `MoverViejitosdb`.`Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MoverViejitosdb`.`Paciente` ;

CREATE TABLE IF NOT EXISTS `MoverViejitosdb`.`Paciente` (
  `idPaciente` INT GENERATED ALWAYS AS () VIRTUAL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Apellidos` VARCHAR(100) NOT NULL,
  `Fecha_Nac` DATE NOT NULL,
  `Mail` VARCHAR(300) NOT NULL,
  `Pass` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MoverViejitosdb`.`Doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MoverViejitosdb`.`Doctor` ;

CREATE TABLE IF NOT EXISTS `MoverViejitosdb`.`Doctor` (
  `Nombre` VARCHAR(100) NOT NULL,
  `Apellidos` VARCHAR(200) NOT NULL,
  `Pass` VARCHAR(100) NOT NULL,
  `Cedula` VARCHAR(300) NOT NULL,
  `Mail` VARCHAR(300) NOT NULL,
  `Telefono` VARCHAR(100) NOT NULL,
  `Especialidad` VARCHAR(300) NOT NULL,
  `Paciente` LONGTEXT NOT NULL,
  PRIMARY KEY (`Cedula`),
  UNIQUE INDEX `Cedula_UNIQUE` (`Cedula` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MoverViejitosdb`.`Receta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MoverViejitosdb`.`Receta` ;

CREATE TABLE IF NOT EXISTS `MoverViejitosdb`.`Receta` (
  `idReceta` INT GENERATED ALWAYS AS () VIRTUAL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_final` DATE NOT NULL,
  `Via` VARCHAR(300) NOT NULL,
  `Efectos_Adversos` VARCHAR(300) NOT NULL,
  `Notas` LONGTEXT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `Doctor_Cedula` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`idReceta`, `Paciente_idPaciente`, `Doctor_Cedula`),
  INDEX `fk_Receta_Paciente1_idx` (`Paciente_idPaciente` ASC),
  INDEX `fk_Receta_Doctor1_idx` (`Doctor_Cedula` ASC),
  CONSTRAINT `fk_Receta_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `MoverViejitosdb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receta_Doctor1`
    FOREIGN KEY (`Doctor_Cedula`)
    REFERENCES `MoverViejitosdb`.`Doctor` (`Cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MoverViejitosdb`.`Dosis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MoverViejitosdb`.`Dosis` ;

CREATE TABLE IF NOT EXISTS `MoverViejitosdb`.`Dosis` (
  `idDosis` INT GENERATED ALWAYS AS () VIRTUAL,
  `num_pas` INT NOT NULL,
  `Tiempo` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`idDosis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MoverViejitosdb`.`Medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MoverViejitosdb`.`Medicamento` ;

CREATE TABLE IF NOT EXISTS `MoverViejitosdb`.`Medicamento` (
  `idMedicamento` INT GENERATED ALWAYS AS () VIRTUAL,
  `Patente` VARCHAR(100) NOT NULL,
  `Activos` VARCHAR(300) NOT NULL,
  `Mg` INT NOT NULL,
  `Dosis_idDosis` INT NOT NULL,
  PRIMARY KEY (`idMedicamento`),
  INDEX `fk_Medicamento_Dosis_idx` (`Dosis_idDosis` ASC),
  CONSTRAINT `fk_Medicamento_Dosis`
    FOREIGN KEY (`Dosis_idDosis`)
    REFERENCES `MoverViejitosdb`.`Dosis` (`idDosis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MoverViejitosdb`.`Enfermedades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MoverViejitosdb`.`Enfermedades` ;

CREATE TABLE IF NOT EXISTS `MoverViejitosdb`.`Enfermedades` (
  `idEnfermedades` INT GENERATED ALWAYS AS () VIRTUAL,
  `Nombre` VARCHAR(100) NOT NULL,
  `fecha_diag` DATE NOT NULL,
  PRIMARY KEY (`idEnfermedades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MoverViejitosdb`.`Notificaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MoverViejitosdb`.`Notificaciones` ;

CREATE TABLE IF NOT EXISTS `MoverViejitosdb`.`Notificaciones` (
  `idNotificaciones` INT GENERATED ALWAYS AS () VIRTUAL,
  `Medicamento` VARCHAR(200) NOT NULL,
  `Horario` TIME NOT NULL,
  `Notas` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idNotificaciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MoverViejitosdb`.`Receta_Medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MoverViejitosdb`.`Receta_Medicamento` ;

CREATE TABLE IF NOT EXISTS `MoverViejitosdb`.`Receta_Medicamento` (
  `Receta_idReceta` INT NOT NULL,
  `Medicamento_idMedicamento` INT NOT NULL,
  PRIMARY KEY (`Receta_idReceta`, `Medicamento_idMedicamento`),
  INDEX `fk_Receta_has_Medicamento_Medicamento1_idx` (`Medicamento_idMedicamento` ASC),
  INDEX `fk_Receta_has_Medicamento_Receta1_idx` (`Receta_idReceta` ASC),
  CONSTRAINT `fk_Receta_has_Medicamento_Receta1`
    FOREIGN KEY (`Receta_idReceta`)
    REFERENCES `MoverViejitosdb`.`Receta` (`idReceta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receta_has_Medicamento_Medicamento1`
    FOREIGN KEY (`Medicamento_idMedicamento`)
    REFERENCES `MoverViejitosdb`.`Medicamento` (`idMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MoverViejitosdb`.`Enfermedades_Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MoverViejitosdb`.`Enfermedades_Paciente` ;

CREATE TABLE IF NOT EXISTS `MoverViejitosdb`.`Enfermedades_Paciente` (
  `Enfermedades_idEnfermedades` INT NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  PRIMARY KEY (`Enfermedades_idEnfermedades`, `Paciente_idPaciente`),
  INDEX `fk_Enfermedades_has_Paciente_Paciente2_idx` (`Paciente_idPaciente` ASC),
  INDEX `fk_Enfermedades_has_Paciente_Enfermedades2_idx` (`Enfermedades_idEnfermedades` ASC),
  CONSTRAINT `fk_Enfermedades_has_Paciente_Enfermedades2`
    FOREIGN KEY (`Enfermedades_idEnfermedades`)
    REFERENCES `MoverViejitosdb`.`Enfermedades` (`idEnfermedades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enfermedades_has_Paciente_Paciente2`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `MoverViejitosdb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MoverViejitosdb`.`Doctor_Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MoverViejitosdb`.`Doctor_Paciente` ;

CREATE TABLE IF NOT EXISTS `MoverViejitosdb`.`Doctor_Paciente` (
  `Doctor_Cedula` VARCHAR(300) NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  PRIMARY KEY (`Doctor_Cedula`, `Paciente_idPaciente`),
  INDEX `fk_Doctor_has_Paciente_Paciente1_idx` (`Paciente_idPaciente` ASC),
  INDEX `fk_Doctor_has_Paciente_Doctor1_idx` (`Doctor_Cedula` ASC),
  CONSTRAINT `fk_Doctor_has_Paciente_Doctor1`
    FOREIGN KEY (`Doctor_Cedula`)
    REFERENCES `MoverViejitosdb`.`Doctor` (`Cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doctor_has_Paciente_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `MoverViejitosdb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MoverViejitosdb`.`Enfermedades_Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MoverViejitosdb`.`Enfermedades_Paciente` ;

CREATE TABLE IF NOT EXISTS `MoverViejitosdb`.`Enfermedades_Paciente` (
  `Enfermedades_idEnfermedades` INT NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  PRIMARY KEY (`Enfermedades_idEnfermedades`, `Paciente_idPaciente`),
  INDEX `fk_Enfermedades_has_Paciente_Paciente2_idx` (`Paciente_idPaciente` ASC),
  INDEX `fk_Enfermedades_has_Paciente_Enfermedades2_idx` (`Enfermedades_idEnfermedades` ASC),
  CONSTRAINT `fk_Enfermedades_has_Paciente_Enfermedades2`
    FOREIGN KEY (`Enfermedades_idEnfermedades`)
    REFERENCES `MoverViejitosdb`.`Enfermedades` (`idEnfermedades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enfermedades_has_Paciente_Paciente2`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `MoverViejitosdb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
